# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64df079f21bc5422e0f0c2247c3dbb1ae6d4d57fab77480738b17f6c3c4af7a120515c130fb3a1234b964770e349eddfef4df8f0d24a94211a8a59f1cc6455e5

test:
  secret_key_base: 5d9590a0ad8a43ac6d89e9581237399fa1a46cbc3dbb1265cfd09d7adf28f26e0e4db02adab539412fbe2eb83054af5acfcc4fa1adac5539461241a9a07ff29c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: d8ff2fcac3ebb0d9f7a378cd52acc5fc0f52643bb576ab9316d02b3017aa2fbc7f4afbc2e778a5467019c61c5f1986a8fc0fefbf5b96c819766adfbd4519aa0c
